spring:
  application:
    name: pistago-backend

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  datasource:
    url: jdbc:postgresql://localhost:5432/pistago
    username: pistago_user
    password: pistago_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090

pistago:
  jwt:
    secret: 4b6150645367566b5970337336763979244226452948404d6351665468576d5a
    expiration: 86400000
  uploads:
    base-path: /var/www/pistago/uploads
    avatars-dir: avatars
    public-url: https://nacimiento.me/uploads
